language: generic

dist: trusty

matrix:
  include:
    - os: osx
      language: generic
      env: TOXENV=py27
  include:
    - os: osx
      language: generic
      env: TOXENV=py26
  fast_finish: true

# osx deps
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python &>/dev/null || brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv; fi
  - pip install py2app
install:
  - python setup.py py2app -A
  - scripts/make-leelaz.sh
  - curl -O https://zero.sjeng.org/best-network
  - | gsed -i \
    -e '90s|^.*$|command = leelaz|'\
    -e '91s|^.*$|parameters = --gtp --noponder --weights best-network'\
    -e '96s|^.*$|command = leelaz|'\
    -e '97s|^.*$|parameters = --gtp --noponder --weights best-network|' \
    config.ini
  - mv config.ini best-network leelaz dist/GoReviewPartner.app/Contents/MacOS/
deploy:
  provider: releases
  api_key: "97c141dba50f337005ba8bde2bfff7245cc90d35"
  file: "dist/GoReviewPartner.app"
  skip_cleanup: true
  on:
    tags: true
