language: generic
dist: trusty
matrix:
  include:
  - os: osx
    language: generic
    env: TOXENV=py26
  fast_finish: true
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python &>/dev/null || brew install
  python; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-sed; fi
- pip install py2app
install:
- python setup.py py2app -A
- scripts/make-leelaz.sh
- curl -O https://zero.sjeng.org/best-network
- |
  gsed -i \
  -e '90s|^.*$|command = leelaz|'\
  -e '91s|^.*$|parameters = --gtp --noponder --weights best-network|'\
  -e '96s|^.*$|command = leelaz|'\
  -e '97s|^.*$|parameters = --gtp --noponder --weights best-network|' \
  config.ini
- mv config.ini best-network leelaz dist/GoReviewPartner.app/Contents/MacOS/
deploy:
  provider: releases
  api_key:
    secure: Lseud0CFNifNX2q2Lxf9J8LboW6ME82n8Vt4lutV48mo7Ik/JigmiFRx/DPFKaiHnUl+Fhcsr/Jszuuo4LILngW6Wcbnnxm+inZBNgvyRryMtwUrU4vs9ZwMR8+/yJ2uV/LeJInttZc3eSY5AgMZLs667/Vymd+yO8Lh3ZMggHJm9l5WMoXz+lq/zt1n1tTPl0mlZWakeQ57QSIkxq9UO22G7zXBcX6XqpukR1BnzKOTJmwUfs/584rTnCdFrWF7xeoSY3SAbQag8h84OiD7FXmQMSzuU+sRMpT52m108RfmC1ZcE8bH6syAG2uVFJAzafL0Aw+vash8RDEJ9vNxYW1iY1JMLa6bDkL9fhcFTXJcU+mnFCHfq0lYh4P9sVxCSJVnncJizIY02xTBzQ+4BnS7ickEciZNOhlMP+KSjoVXCN5TpHjZZiR6ah2vHuITLehiAQT/F8IErw7ZD8ALZJaMi3m/v4cs11m9Yy5meNQuT3dhJnSejcc2XsfUEHm9Hgu1NzBPdrxUftb07RZAPxBo9l4SwBBZ82J9nPoTDDvPAvXK6qphkjuh+LO8WsPPXqCoQB4Ikao4l1ACRssOHItBau4ZaLIsFHiCv8wqRKwo1L3udpvi9Buvmi7dsTyOlLDoyMug0L+cNy8dwKg9EOWN+YOQr28BRkJ6q5GMf0Y=
  skip_cleanup: true
  file: dist/GoReviewPartner.app
  on:
    repo: alexpenson/goreviewpartner
    tags: true
    all_branches: true